app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['web','auth']], function () {
	Route::resource('projects', 'ProjectController');
	Route::get('projects/{id}/tasks', 'ProjectController@taskList');
	Route::get('projects/{id}/create_task', 'ProjectController@createTask');
	Route::post('projects/{id}', 'ProjectController@storeTask');
});
Route::auth();

Route::get('/home', 'HomeController@index');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model
{
    use SoftDeletes;
	protected $fillable = ['project_name', 'project_description'];
	protected $dates = ['deleted_at'];

	public function addTask($task) {
		$this->tasks()->save($task);
	}

	public function scopeEverything($query) {
		return $query->withTrashed();
	}

	public function user() {
		return $this->belongsTo('App\User');
	}

	public function tasks() {
		return $this->hasMany('App\Task');
	}

}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['task'];

    public function getStatusAttribute($value) {
    	return ($value) ? 'done' : 'not done';
    }

    public function project()
    {
        return $this->belongsTo('App\Project');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function addProject($project) {
        $this->projects()->save($project);
    }

    public function projects() {
        return $this->hasMany('App\Project');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Project;
use Auth;
use Gate;

class ProjectController extends Controller
{
    public function index() {

    	$project_list = Project::everything()->get();
    	return view('projects.index', compact('project_list'));
    }

    public function create() {
    	return view('projects.create');
    }

    public function store(Request $request) {
    	$user = Auth::user();
    	$project = new Project($request->all());
    	$user->addProject($project);
    	return redirect('projects');
    }

    public function show($id) {
		$project = Project::findOrFail($id);
    	return view('projects.show', compact('project'));    	
    }

    public function edit($id) {
    	$project = Project::findOrFail($id);
    	return view('projects.edit', compact('project'));
    }

    public function update(Request $request, $id) {

    	$project = Project::findOrFail($id);
		if (Gate::denies('update', $project)) {
            abort(403);
        }
    	$project->update($request->only('project_name', 'project_description'));

    	return redirect('projects');
    }

    public function destroy($id) {
    	$project = Project::findOrFail($id);
    	if (Gate::denies('delete', $project)) {
            abort(403);
        }
        $project->delete();
    	return redirect('projects');
    }

    public function createTask($id) {
    	return view('projects.create_task', compact('id'));
    }

    public function storeTask(Request $request, $id) {
    	$task = new \App\Task($request->only('task'));
    	$project = Project::findOrFail($id);
    	$project->addTask($task);
    	return redirect("projects/$id");
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                    <li><a href="{{ url('/projects') }}">Projects</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}

    @stack('script');
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<title>Greg Hermo Test Repo</title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	

</head>
<body>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
		@if(Session::has('flash_message'))
	    	<div class="alert alert-success">
	    		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
		    	{{ Session::get('flash_message') }}
	    	</div>
		@endif
		@yield('content')
		</div>
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

	@stack('script');

</body>	
</html>

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">New Project</div>

                <div class="panel-body">
                    <form method="post" action="{{ url('projects') }}">

					<input type="hidden" name="_token" value="{{ csrf_token() }}">

					<div class="form-group">
					<label for="project_name">Project Name:</label>
					<input type="text" name="project_name" class="form-control" />
					</div>

					<div class="form-group">
					<label for="project_description">Project Name:</label>
					<input type="text" name="project_description" class="form-control" />
					</div>

					<a href="{{ url('projects') }}">Cancel</a>&nbsp;<input type="submit" />

					</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/create_task.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">New Task</div>

                <div class="panel-body">
                    
					<form method="post" action="{{ url("projects/$id") }}">

					<input type="hidden" name="_token" value="{{ csrf_token() }}">

					<div class="form-group">
					<label for="task">Task</label>
					<input type="text" name="task" class="form-control" />
					</div>

					<a href="{{ url("projects/$id") }}">Cancel</a>&nbsp;<input type="submit" />

					</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">New Project</div>

                <div class="panel-body">
                    
					<form method="post" action="{{ url("projects/$project->id") }}">
					<input name="_method" type="hidden" value="PATCH" />
					<input type="hidden" name="_token" value="{{ csrf_token() }}">

					<div class="form-group">
					<label for="project_name">Project Name:</label>
					<input type="text" name="project_name" class="form-control" value="{{ $project->project_name }}" />
					</div>

					<div class="form-group">
					<label for="project_description">Project Name:</label>
					<input type="text" name="project_description" class="form-control" value="{{ $project->project_description }}"  />
					</div>
					<div class="form-group">
						<p class="text-center">
							<a href="{{ url('projects') }}">Cancel</a>&nbsp;<input type="submit" />
						</p>
					</div>
					<div class="form-group">
						<p class="text-right"><a href="#" id="delete" class="btn-sm btn-danger">Delete</a></p>
					</div>

					</form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('script')
<script>
(function($) {
	$('#delete').click(function() {
		$(this).closest('form').find("input[name='_method']").val('DELETE');
		$(this).closest('form').submit();
	});
})(jQuery);
</script>
@endpush

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Projects ({{ $project_list->count() }})</div>

                <div class="panel-body">	
					<a href="{{ url('projects/create') }}" class="btn btn-primary">New Project</a>
					<table class="table">
						<thead>
							<tr>
								<th>Name</th>
								<th>Description</th>
								<th>Created By</th>
								<th>Timestamps</th>
								<th>Action</th>
							</tr>
						</thead>
						@foreach($project_list as $project)
						<tr>
							<td>{{$project->project_name}}</td>
							<td>{{$project->project_description}}</td>
							<td>{{$project->user->name}}</td>
							<td>
								Created at: {{$project->created_at}}<br/>
								Updated at: {{$project->updated_at}}<br/>
								Deleted at: {{$project->deleted_at}}<br/>
							</td>
							<td><a href="{{ url("projects/$project->id") }}">View</a>@can('update', $project) | <a href="{{ url("projects/$project->id/edit") }}">Edit</a>@endcan</td>
							
						</tr>
						@endforeach
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $project->project_name }}&nbsp;<small>{{$project->project_description}}</div>

                <div class="panel-body">
                	<h2>Tasks ({{ $project->tasks->count() }})</h2>
                    <a href="{{ url('projects') }}" class="btn btn-default">Back</a>
					<a href="{{ url("projects/$project->id/create_task") }}" class="btn btn-primary">New Task</a>
					<table class="table">
						<thead>
							<tr>
								<th>Task</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
						</thead>
						@foreach($project->tasks as $task)
							<tr>
								<td>{{$task->task}}</td>
								<td>{{$task->status}}</td>
								<td>Edit | Delete</td>
							</tr>
						@endforeach
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection